### ISSUE TITLE
pip install missing packages

### ISSUE THREAD

**Issue by DeoLeung** [ozak/georasters#20]
using python 3.5.2 under mac, extra install needed
```
pip install affine rasterstats
```

**Comment by ozak** [comment]
Hi @DeoLeung. It is strange that you are getting this error, since those are part of the requirements so they should be getting installed automatically. Not sure what may be causing this issue in your install, haven't seen it in other installations I have tried.

**Comment by ozak** [comment]
Was this the ``conda`` install?

**Comment by ozak** [comment]
@DeoLeung I never heard back from you.

**Comment by DeoLeung** [comment]
it's a normal pip install from virtual environment, I tried it from a new
created virtualenv the problem persists

**Comment by ozak** [comment]
@DeoLeung strange, not sure what could be causing this, not have I heard from other people having this issue. I'll try to research.

**Comment by DeoLeung** [comment]
here's the terminal log, also `numpy` needs to be manually install first due to `scikit-image`
<details>
<summary>pip install</summary><p>

```sh
(test) $ pip install --trusted-host pypi.doubanio.com -i http://pypi.doubanio.com/simple/ georasters
Collecting georasters
  Downloading http://pypi.doubanio.com/packages/10/11/b7ed774362775d7b20ac019e1695f2a3188040a19a2fb9995dbe2267c677/georasters-0.5.6.tar.gz
Collecting numpy (from georasters)
  Downloading http://pypi.doubanio.com/packages/e9/57/a204d3eaefc5ba2bb3d93ac1b93d1ab755d3874ab3d9c33a897e9f79b035/numpy-1.12.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.4MB)
    100% |████████████████████████████████| 4.4MB 8.6MB/s
Collecting GDAL (from georasters)
  Downloading http://pypi.doubanio.com/packages/36/d7/f89ac1347185db56939c156330efbfa2e3be560060b74e31f41e514ee627/GDAL-2.1.3.tar.gz (413kB)
    100% |████████████████████████████████| 419kB 5.8MB/s
Collecting docopt (from georasters)
  Downloading http://pypi.doubanio.com/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Collecting pandas (from georasters)
  Downloading http://pypi.doubanio.com/packages/5f/d6/bbefbb8b46271fe30c3859937b395602ed7c586c42cd413ea9557950d5e9/pandas-0.19.2-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (11.8MB)
    100% |████████████████████████████████| 11.8MB 5.8MB/s
Collecting pyproj (from georasters)
  Downloading http://pypi.doubanio.com/packages/29/72/5c1888c4948a0c7b736d10e0f0f69966e7c0874a660222ed0a2c2c6daa9f/pyproj-1.9.5.1.tar.gz (4.4MB)
    100% |████████████████████████████████| 4.4MB 8.6MB/s
Collecting scikit-image (from georasters)
  Downloading http://pypi.doubanio.com/packages/86/d0/b0192dc9a544da90f2d9150bcd84b981c6873e42a1f752b6affb89180ad8/scikit-image-0.12.3.tar.gz (20.7MB)
    100% |████████████████████████████████| 20.7MB 2.7MB/s
    Complete output from command python setup.py egg_info:
    To install scikit-image from source, you will need numpy.
    Install numpy with pip:
    pip install numpy
    Or use your operating system package manager. For more
    details, see http://scikit-image.org/docs/stable/install.html

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/5r/d1xb2ck920zgnsj039lzg5gm0000gn/T/pip-build-9yt96jt2/scikit-image/
(test) $ pip install --trusted-host pypi.doubanio.com -i http://pypi.doubanio.com/simple/ numpy
Collecting numpy
  Downloading http://pypi.doubanio.com/packages/e9/57/a204d3eaefc5ba2bb3d93ac1b93d1ab755d3874ab3d9c33a897e9f79b035/numpy-1.12.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.4MB)
    100% |████████████████████████████████| 4.4MB 9.0MB/s
Installing collected packages: numpy
Successfully installed numpy-1.12.1
(test)$ pip install --trusted-host pypi.doubanio.com -i http://pypi.doubanio.com/simple/ georasters
Collecting georasters
  Downloading http://pypi.doubanio.com/packages/10/11/b7ed774362775d7b20ac019e1695f2a3188040a19a2fb9995dbe2267c677/georasters-0.5.6.tar.gz
Requirement already satisfied: numpy in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from georasters)
Collecting GDAL (from georasters)
  Downloading http://pypi.doubanio.com/packages/36/d7/f89ac1347185db56939c156330efbfa2e3be560060b74e31f41e514ee627/GDAL-2.1.3.tar.gz (413kB)
    100% |████████████████████████████████| 419kB 9.5MB/s
Collecting docopt (from georasters)
  Downloading http://pypi.doubanio.com/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Collecting pandas (from georasters)
  Downloading http://pypi.doubanio.com/packages/5f/d6/bbefbb8b46271fe30c3859937b395602ed7c586c42cd413ea9557950d5e9/pandas-0.19.2-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (11.8MB)
    100% |████████████████████████████████| 11.8MB 6.3MB/s
Collecting pyproj (from georasters)
  Downloading http://pypi.doubanio.com/packages/29/72/5c1888c4948a0c7b736d10e0f0f69966e7c0874a660222ed0a2c2c6daa9f/pyproj-1.9.5.1.tar.gz (4.4MB)
    100% |████████████████████████████████| 4.4MB 7.0MB/s
Collecting scikit-image (from georasters)
  Downloading http://pypi.doubanio.com/packages/86/d0/b0192dc9a544da90f2d9150bcd84b981c6873e42a1f752b6affb89180ad8/scikit-image-0.12.3.tar.gz (20.7MB)
    100% |████████████████████████████████| 20.7MB 4.5MB/s
Collecting matplotlib (from georasters)
  Downloading http://pypi.doubanio.com/packages/6b/df/c2fe78861c52de30aa93169ee37e0407c9b551ff68042fc1eacc209f7e39/matplotlib-2.0.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (12.8MB)
    100% |████████████████████████████████| 12.8MB 9.4MB/s
Collecting python-dateutil>=2 (from pandas->georasters)
  Downloading http://pypi.doubanio.com/packages/40/8b/275015d7a9ec293cf1bbf55433258fbc9d0711890a7f6dc538bac7b86bce/python_dateutil-2.6.0-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 668kB/s
Collecting pytz>=2011k (from pandas->georasters)
  Downloading http://pypi.doubanio.com/packages/f5/fa/4a9aefc206aa49a4b5e0a72f013df1f471b4714cdbe6d78f0134feeeecdb/pytz-2016.10-py2.py3-none-any.whl (483kB)
    100% |████████████████████████████████| 491kB 9.4MB/s
Collecting scipy>=0.9.0 (from scikit-image->georasters)
  Downloading http://pypi.doubanio.com/packages/35/5c/88a2f023cbadf3d84520cc9c3bffa0da93480a08f28a4d07f2a5543c71a9/scipy-0.19.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (16.2MB)
    100% |████████████████████████████████| 16.2MB 11.5MB/s
Requirement already satisfied: six>=1.7.3 in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from scikit-image->georasters)
Collecting networkx>=1.8 (from scikit-image->georasters)
  Downloading http://pypi.doubanio.com/packages/d3/2c/e473e54afc9fae58dfa97066ef6709a7e35a1dd1c28c5a3842989322be00/networkx-1.11-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 9.4MB/s
Collecting pillow>=2.1.0 (from scikit-image->georasters)
  Downloading http://pypi.doubanio.com/packages/4f/ec/b39ee6a4fd9e7d43d8c72a26ea319e429dfce9aa98b665c48f7181fbc3e5/Pillow-4.0.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.4MB)
    100% |████████████████████████████████| 3.4MB 6.7MB/s
Collecting dask[array]>=0.5.0 (from scikit-image->georasters)
  Downloading http://pypi.doubanio.com/packages/ae/4e/ecb4430a42b49d65e9ae53548fd672578201709d3e0c1fba91b8d4f4a016/dask-0.14.1-py2.py3-none-any.whl (463kB)
    100% |████████████████████████████████| 471kB 9.5MB/s
Collecting cycler>=0.10 (from matplotlib->georasters)
  Downloading http://pypi.doubanio.com/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Requirement already satisfied: pyparsing!=2.0.0,!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from matplotlib->georasters)
Collecting decorator>=3.4.0 (from networkx>=1.8->scikit-image->georasters)
  Downloading http://pypi.doubanio.com/packages/00/cc/dd79ea98a0ff5a01d714c37eddd99cd0a71557113f1511921d1ef9a083b8/decorator-4.0.11-py2.py3-none-any.whl
Collecting olefile (from pillow>=2.1.0->scikit-image->georasters)
  Downloading http://pypi.doubanio.com/packages/35/17/c15d41d5a8f8b98cc3df25eb00c5cee76193114c78e5674df6ef4ac92647/olefile-0.44.zip (74kB)
    100% |████████████████████████████████| 81kB 2.4MB/s
Collecting toolz>=0.7.3; extra == "array" (from dask[array]>=0.5.0->scikit-image->georasters)
Building wheels for collected packages: georasters, GDAL, docopt, pyproj, scikit-image, olefile
  Running setup.py bdist_wheel for georasters ... done
  Stored in directory: /Users/xxx/Library/Caches/pip/wheels/73/c8/51/49506eaf37dbf7269e28e06ea7ffc39579c7ae3f40411c7d53
  Running setup.py bdist_wheel for GDAL ... done
  Stored in directory: /Users/xxx/Library/Caches/pip/wheels/7b/a6/11/a9c0efddd9a2d72e317418e65a1694ff78ba20dbef344e5b84
  Running setup.py bdist_wheel for docopt ... done
  Stored in directory: /Users/xxx/Library/Caches/pip/wheels/35/30/e2/27624e4cd469253b6db0dae0c2994b500f8268b6e924706cfc
  Running setup.py bdist_wheel for pyproj ... done
  Stored in directory: /Users/xxx/Library/Caches/pip/wheels/56/b0/90/9a79668361e7e05ed70985d394a3a84aadeae3c47da568d3bd
  Running setup.py bdist_wheel for scikit-image ... done
  Stored in directory: /Users/xxx/Library/Caches/pip/wheels/31/b4/ca/8439c684b8c9f9c406e35b432cbc4f57b5622d14a318572bc0
  Running setup.py bdist_wheel for olefile ... done
  Stored in directory: /Users/xxx/Library/Caches/pip/wheels/c6/32/0c/6a407523ea98c4a86071bedc4a542df3d0f52f27a639004788
Successfully built georasters GDAL docopt pyproj scikit-image olefile
Installing collected packages: GDAL, docopt, python-dateutil, pytz, pandas, pyproj, cycler, matplotlib, scipy, decorator, networkx, olefile, pillow, toolz, dask, scikit-image, georasters
Successfully installed GDAL-2.1.3 cycler-0.10.0 dask-0.14.1 decorator-4.0.11 docopt-0.6.2 georasters-0.5.6 matplotlib-2.0.0 networkx-1.11 olefile-0.44 pandas-0.19.2 pillow-4.0.0 pyproj-1.9.5.1 python-dateutil-2.6.0 pytz-2016.10 scikit-image-0.12.3 scipy-0.19.0 toolz-0.8.2
(test) $ python
Python 3.6.0 (default, Dec 24 2016, 00:01:50)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import georasters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxx/.virtualenvs/test/lib/python3.6/site-packages/georasters/__init__.py", line 3, in <module>
    from .georasters import get_geo_info, map_pixel, map_pixel_inv, aggregate, create_geotiff, align_rasters, \
  File "/Users/xxx/.virtualenvs/test/lib/python3.6/site-packages/georasters/georasters.py", line 38, in <module>
    import matplotlib.pyplot as plt
  File "/Users/xxx/.virtualenvs/test/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/xxx/.virtualenvs/test/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/Users/xxx/.virtualenvs/test/lib/python3.6/site-packages/matplotlib/backends/backend_macosx.py", line 19, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
>>>

(test) $ python
Python 3.6.0 (default, Dec 24 2016, 00:01:50)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.use('TkAgg')
>>> import georasters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxx/.virtualenvs/test/lib/python3.6/site-packages/georasters/__init__.py", line 3, in <module>
    from .georasters import get_geo_info, map_pixel, map_pixel_inv, aggregate, create_geotiff, align_rasters, \
  File "/Users/xxx/.virtualenvs/test/lib/python3.6/site-packages/georasters/georasters.py", line 40, in <module>
    from fiona.crs import from_string
ModuleNotFoundError: No module named 'fiona'
>>>
(test) $ pip install --trusted-host pypi.doubanio.com -i http://pypi.doubanio.com/simple/ fiona
Collecting fiona
  Downloading http://pypi.doubanio.com/packages/cc/63/2f333a084dbbeb99d5c5288914a232a059655b14548ff97109655ff64f00/Fiona-1.7.5-cp36-cp36m-macosx_10_6_intel.whl (17.7MB)
    100% |████████████████████████████████| 17.7MB 3.9MB/s
Collecting munch (from fiona)
  Downloading http://pypi.doubanio.com/packages/84/dc/d897cb427f15029e04745a3de611d8ed3d97e9a0ef894547a0ba261f2807/munch-2.1.1.tar.gz
Requirement already satisfied: six in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from fiona)
Collecting click-plugins (from fiona)
Collecting cligj (from fiona)
  Downloading http://pypi.doubanio.com/packages/fc/05/e8384e1f7c8689cd1b91818a24cc860077c73368fb285ba53fbd8556ec98/cligj-0.4.0-py3-none-any.whl
Collecting click>=3.0 (from click-plugins->fiona)
  Downloading http://pypi.doubanio.com/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 2.1MB/s
Building wheels for collected packages: munch
  Running setup.py bdist_wheel for munch ... done
  Stored in directory: /Users/xxx/Library/Caches/pip/wheels/44/c9/a0/45c5959be6a0c7297d9f1d5dd987a47dff8db2dbada97b1d23
Successfully built munch
Installing collected packages: munch, click, click-plugins, cligj, fiona
Successfully installed click-6.7 click-plugins-1.0.3 cligj-0.4.0 fiona-1.7.5 munch-2.1.1
(test)$ python
Python 3.6.0 (default, Dec 24 2016, 00:01:50)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.use('TkAgg')
>>> import georasters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxx/.virtualenvs/test/lib/python3.6/site-packages/georasters/__init__.py", line 3, in <module>
    from .georasters import get_geo_info, map_pixel, map_pixel_inv, aggregate, create_geotiff, align_rasters, \
  File "/Users/xxx/.virtualenvs/test/lib/python3.6/site-packages/georasters/georasters.py", line 41, in <module>
    import geopandas as gp
ModuleNotFoundError: No module named 'geopandas'
>>>
(test)$ pip install --trusted-host pypi.doubanio.com -i http://pypi.doubanio.com/simple/ geopandas
Collecting geopandas
  Downloading http://pypi.doubanio.com/packages/dd/3c/cb764cd41a72efcb1424d4109137c18a94900632bdb43d5b298987eba609/geopandas-0.2.1-py2.py3-none-any.whl (199kB)
    100% |████████████████████████████████| 204kB 1.8MB/s
Collecting shapely (from geopandas)
  Downloading http://pypi.doubanio.com/packages/8d/12/6079549471d2d5ac2b20274ab3bd7c896658914340d1242080b0a2e08990/Shapely-1.5.17.post1-cp36-cp36m-macosx_10_6_intel.whl (2.1MB)
    100% |████████████████████████████████| 2.1MB 8.5MB/s
Requirement already satisfied: pyproj in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from geopandas)
Requirement already satisfied: pandas in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from geopandas)
Requirement already satisfied: fiona in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from geopandas)
Collecting descartes (from geopandas)
  Downloading http://pypi.doubanio.com/packages/e5/b6/1ed2eb03989ae574584664985367ba70cd9cf8b32ee8cad0e8aaeac819f3/descartes-1.1.0-py3-none-any.whl
Requirement already satisfied: python-dateutil>=2 in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from pandas->geopandas)
Requirement already satisfied: pytz>=2011k in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from pandas->geopandas)
Requirement already satisfied: numpy>=1.7.0 in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from pandas->geopandas)
Requirement already satisfied: munch in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from fiona->geopandas)
Requirement already satisfied: cligj in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from fiona->geopandas)
Requirement already satisfied: click-plugins in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from fiona->geopandas)
Requirement already satisfied: six in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from fiona->geopandas)
Requirement already satisfied: matplotlib in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from descartes->geopandas)
Requirement already satisfied: click>=4.0 in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from cligj->fiona->geopandas)
Requirement already satisfied: cycler>=0.10 in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from matplotlib->descartes->geopandas)
Requirement already satisfied: pyparsing!=2.0.0,!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from matplotlib->descartes->geopandas)
Installing collected packages: shapely, descartes, geopandas
Successfully installed descartes-1.1.0 geopandas-0.2.1 shapely-1.5.17.post1
(test)$ python
Python 3.6.0 (default, Dec 24 2016, 00:01:50)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.use('TkAgg')
>>> import georasters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxx/.virtualenvs/test/lib/python3.6/site-packages/georasters/__init__.py", line 3, in <module>
    from .georasters import get_geo_info, map_pixel, map_pixel_inv, aggregate, create_geotiff, align_rasters, \
  File "/Users/xxx/.virtualenvs/test/lib/python3.6/site-packages/georasters/georasters.py", line 43, in <module>
    from affine import Affine
ModuleNotFoundError: No module named 'affine'
>>>
(test)$ pip install --trusted-host pypi.doubanio.com -i http://pypi.doubanio.com/simple/ affine
Collecting affine
  Downloading http://pypi.doubanio.com/packages/bf/df/d175613af5ec13cfe83e8bc1249f647ca6d55dd33565ce9433cf0e00daa9/affine-2.0.0.post1-py3-none-any.whl
Installing collected packages: affine
Successfully installed affine-2.0.0.post1
(test)$ python
Python 3.6.0 (default, Dec 24 2016, 00:01:50)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.use('TkAgg')
>>> import georasters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxx/.virtualenvs/test/lib/python3.6/site-packages/georasters/__init__.py", line 3, in <module>
    from .georasters import get_geo_info, map_pixel, map_pixel_inv, aggregate, create_geotiff, align_rasters, \
  File "/Users/xxx/.virtualenvs/test/lib/python3.6/site-packages/georasters/georasters.py", line 44, in <module>
    from rasterstats import zonal_stats
ModuleNotFoundError: No module named 'rasterstats'
>>>
(test)$ pip install --trusted-host pypi.doubanio.com -i http://pypi.doubanio.com/simple/ rasterstats
Collecting rasterstats
  Downloading http://pypi.doubanio.com/packages/ce/f8/1219c23bb4a7eab37e127da993475fcdf14bb003bd8b4478a9778442aa43/rasterstats-0.12.0-py2.py3-none-any.whl
Requirement already satisfied: cligj>=0.4 in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from rasterstats)
Requirement already satisfied: fiona in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from rasterstats)
Requirement already satisfied: numpy>=1.9 in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from rasterstats)
Collecting simplejson (from rasterstats)
  Downloading http://pypi.doubanio.com/packages/40/ad/52c1f3a562df3b210e8f165e1aa243a178c454ead65476a39fa3ce1847b6/simplejson-3.10.0.tar.gz (77kB)
    100% |████████████████████████████████| 81kB 1.1MB/s
Collecting rasterio>=0.27 (from rasterstats)
  Downloading http://pypi.doubanio.com/packages/59/f7/040531ab12b4a4522b7fd99eec39258b78b82c67e3adcf81f25ee4a3e544/rasterio-0.36.0.tar.gz (1.2MB)
    100% |████████████████████████████████| 1.2MB 9.6MB/s
Requirement already satisfied: shapely in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from rasterstats)
Requirement already satisfied: click>=4.0 in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from cligj>=0.4->rasterstats)
Requirement already satisfied: munch in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from fiona->rasterstats)
Requirement already satisfied: six in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from fiona->rasterstats)
Requirement already satisfied: click-plugins in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from fiona->rasterstats)
Requirement already satisfied: affine in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from rasterio>=0.27->rasterstats)
Collecting snuggs (from rasterio>=0.27->rasterstats)
  Downloading http://pypi.doubanio.com/packages/23/dd/f8a42549be3f02af7f1edd583b4b0a7e946e330aa2cef48a9bd2f43b87fa/snuggs-1.4.1-py3-none-any.whl
Requirement already satisfied: pyparsing in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from snuggs->rasterio>=0.27->rasterstats)
Building wheels for collected packages: simplejson, rasterio
  Running setup.py bdist_wheel for simplejson ... done
  Stored in directory: /Users/xxx/Library/Caches/pip/wheels/d1/57/97/6de1217a39161323e0c83f93deb8f70ec13c8917008b76086a
  Running setup.py bdist_wheel for rasterio ... done
  Stored in directory: /Users/xxx/Library/Caches/pip/wheels/d0/87/ed/4cd9baab95d95ce39d7b94cfb403c697d511cd0833020b6ce2
Successfully built simplejson rasterio
Installing collected packages: simplejson, snuggs, rasterio, rasterstats
Successfully installed rasterio-0.36.0 rasterstats-0.12.0 simplejson-3.10.0 snuggs-1.4.1
(test)$ python
Python 3.6.0 (default, Dec 24 2016, 00:01:50)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.use('TkAgg')
>>> import georasters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxx/.virtualenvs/test/lib/python3.6/site-packages/georasters/__init__.py", line 3, in <module>
    from .georasters import get_geo_info, map_pixel, map_pixel_inv, aggregate, create_geotiff, align_rasters, \
  File "/Users/xxx/.virtualenvs/test/lib/python3.6/site-packages/georasters/georasters.py", line 45, in <module>
    import pysal
ModuleNotFoundError: No module named 'pysal'
>>>
(test)$ pip install --trusted-host pypi.doubanio.com -i http://pypi.doubanio.com/simple/ pysal
Collecting pysal
Requirement already satisfied: scipy>=0.11 in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from pysal)
Requirement already satisfied: numpy>=1.3 in /Users/xxx/.virtualenvs/test/lib/python3.6/site-packages (from pysal)
Installing collected packages: pysal
Successfully installed pysal-1.13.0
(test)$ python
Python 3.6.0 (default, Dec 24 2016, 00:01:50)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.use('TkAgg')
>>> import georasters
>>>
```

</p>
</details>

**Comment by ozak** [comment]
Ok. I think it should be resolved now. Do you mind giving it another try and letting me know?

**Comment by DeoLeung** [comment]
perfect, verified
