### ISSUE TITLE
Issues with first example

### ISSUE THREAD

**Issue by marthinwurer** [ozak/georasters#28]
test.py is the first example in the readme with a different raster as the default.

```
$ cat test.py 
import georasters as gr

# Load data
raster = "./ilatlon.tif"
data = gr.from_file(raster)

# Plot data
data.plot()

# Get some stats
data.mean()
data.sum()
data.std()

# Convert to Pandas DataFrame
df = data.to_pandas()

# Save transformed data to GeoTiff
data2 = data**2
data2.to_tiff('./data2')

# Algebra with rasters
data3 = np.sin(data.raster) / data2
data3.plot()

# Notice that by using the data.raster object, 
# you can do any mathematical operation that handles 
# Numpy Masked Arrays

# Find value at point (x,y) or at vectors (X,Y)
value = data.map_pixel(x,y)
Value = data.map_pixel(X,Y)
```

When run, it crashes because numpy is not imported:
```
$ python test.py
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    data3 = np.sin(data.raster) / data2
NameError: name 'np' is not defined
```
Once numpy is imported, the test runs, but it does have some errors:
```
$ python test.py 
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    data2.to_tiff('./data2')
  File "/home/benjamin/.pyenv/versions/georasters/lib/python3.6/site-packages/georasters/georasters.py", line 477, in to_tiff
    self.raster.data[self.raster.mask] = self.nodata_value
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

If I'm doing something wrong, I'd love to know.

**Comment by ozak** [comment]
Does your ``data`` have a ``nodata_value``? The error seems to suggest the raster ``data2`` has no ``nodata_value``, which it should have copied from ``data``.  What do you get when you execute

```python
data.nodata_value
data2.nodata_value
```

**Comment by marthinwurer** [comment]
Both come back as `None`.

**Comment by ozak** [comment]
That is the problem. Your rasters are supposed to have a ``nodata_value``. I have been debating about forcing ``-np.inf`` if there is none, but I think it is better that users get an error so they are aware that it is missing.
