### ISSUE TITLE
Issue with conda virtual environment file (  try_georasters3.yml creates a GIS functional python-3.5 environment.)

### ISSUE THREAD

**Issue by immuhammadadil** [ozak/georasters#42]
(try_georasters3) adil@adil-HP-Pavilion-Notebook:~/burkstream$ python3 sample.py
Traceback (most recent call last):
  File "sample.py", line 1, in <module>
    import georasters as gr
  File "/home/adil/anaconda3/envs/try_georasters3/lib/python3.5/site-packages/georasters/__init__.py", line 3, in <module>
    from .georasters import get_geo_info, map_pixel, map_pixel_inv, aggregate, create_geotiff, align_rasters, \
  File "/home/adil/anaconda3/envs/try_georasters3/lib/python3.5/site-packages/georasters/georasters.py", line 33, in <module>
    from osgeo import gdal, gdalnumeric, ogr, osr, gdal_array
  File "/home/adil/anaconda3/envs/try_georasters3/lib/python3.5/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/adil/anaconda3/envs/try_georasters3/lib/python3.5/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/adil/anaconda3/envs/try_georasters3/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/adil/anaconda3/envs/try_georasters3/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libpoppler.so.76: cannot open shared object file: No such file or directory

**Comment by ozak** [comment]
It's hard to know from the information you provided what fails, but does not seem to be related to ``georasters``. I would suggest installing using ``conda`` or ``pip`` in a fresh environment, which should minimize old dependencies etc.

**Comment by ozak** [comment]
From #43 I imagine it implies you were able to install and make it work, so I will close this issue.

**Comment by immuhammadadil** [comment]
Yes, I solved the issue by setting up conda environment
