### ISSUE TITLE
If there is no valid no data value, file loading fails.

### ISSUE THREAD

**Issue by marthinwurer** [ozak/georasters#47]
Line of code and stack trace:
```
>>> raster = gr.from_file(os.path.expanduser("~/Downloads/datasets/elevation/one_deg.tif"))
Traceback (most recent call last):
  File "/home/benjamin/.pyenv/versions/georasters/lib/python3.7/site-packages/numpy/ma/core.py", line 473, in _check_fill_value
    fill_value = np.array(fill_value, copy=False, dtype=ndtype)
ValueError: cannot convert float NaN to integer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/benjamin/.pyenv/versions/georasters/lib/python3.7/site-packages/georasters/georasters.py", line 1231, in from_file
    data = np.ma.masked_array(data, mask=data == ndv, fill_value=ndv)
  File "/home/benjamin/.pyenv/versions/georasters/lib/python3.7/site-packages/numpy/ma/core.py", line 2893, in __new__
    _data._fill_value = _check_fill_value(fill_value, _data.dtype)
  File "/home/benjamin/.pyenv/versions/georasters/lib/python3.7/site-packages/numpy/ma/core.py", line 479, in _check_fill_value
    raise TypeError(err_msg % (fill_value, ndtype))
TypeError: Cannot convert fill_value nan to dtype int16
```

I dumped this file using the `to_tiff` method. I then tried to load it again, and got this stack trace.  Are there any workarounds?

**Comment by ozak** [comment]
I would create the file with a ``ndv``.  Just assign it to the raster before saving (this needs you to change the underlying masked raster). Seems not well defined if ``ndv`` is missing. Although I think it would be good to have an informative message or some workaround.

**Comment by marthinwurer** [comment]
I'd think that a warning message and a default no data value for each type would be good. Numpy's masked array library has a function that can get a standard default value for each of their data types, `np.ma.core.default_fill_value()`. We could use that for unknowns and throw a warning or something.

**Comment by ozak** [comment]
sounds good
